name: Publish Docker image
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  publish-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Cloudflare WARP
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloudflare-client-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-client-archive-keyring.gpg] https://pkg.cloudflareclient.com focal main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp
          cp /usr/bin/warp-cli /usr/bin/warp-svc .
      - name: Prepare Docker image build metadata
        id: prepare-docker-image-build-metadata
        run: |
          DOCKER_IMAGE_TAG=$(./warp-cli --version | sed "s/WARP //")
          DOCKER_IMAGE_BUILD_ARG_CLOUDFLARE_WARP_VERSION=$(dpkg -s cloudflare-warp | grep Version | sed "s/Version //")
          echo "::set-output name=docker-image-tag::$DOCKER_IMAGE_TAG"
          echo "::set-output name=docker-image-build-arg-cloudflare-warp-version::$DOCKER_IMAGE_BUILD_ARG_CLOUDFLARE_WARP_VERSION"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{github.token}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: CLOUDFLARE_WARP_VERSION=${{steps.prepare-docker-image-build-metadata.outputs.docker-image-build-arg-cloudflare-warp-version}}
          push: ${{github.event_name != 'pull_request'}}
          tags: |
            ${{secrets.DOCKER_USERNAME}}/cloudflare-warp:${{steps.prepare-docker-image-build-metadata.outputs.docker-image-tag}}
            ${{secrets.DOCKER_USERNAME}}/cloudflare-warp:latest
            ghcr.io/${{github.repository_owner}}/cloudflare-warp:${{steps.prepare-docker-image-build-metadata.outputs.docker-image-tag}}
            ghcr.io/${{github.repository_owner}}/cloudflare-warp:latest
