name: Publish Docker image
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  publish-docker-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Cloudflare WARP
        run: |
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloudflare-client-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-client-archive-keyring.gpg] https://pkg.cloudflareclient.com focal main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y cloudflare-warp
          cp /usr/bin/warp-cli /usr/bin/warp-svc .
      - name: Build and push Docker image
        run: |
          DOCKER_IMAGE_REPO=${{secrets.DOCKER_USERNAME}}/cloudflare-warp
          DOCKER_IMAGE_TAG=$(./warp-cli --version | sed "s/WARP //")
          DOCKER_IMAGE_TAG_HTTP_CODE=$(curl -sL -w "%{http_code}" -o /dev/null https://hub.docker.com/v2/repositories/$DOCKER_IMAGE_REPO/tags/$DOCKER_IMAGE_TAG/)
          sudo docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
          sudo docker build --tag $DOCKER_IMAGE_REPO:$DOCKER_IMAGE_TAG --tag $DOCKER_IMAGE_REPO:latest .
          if [[ ${{github.event_name}} != "pull_request" && $DOCKER_IMAGE_TAG_HTTP_CODE == 404 ]]; then
            for IMG in $DOCKER_IMAGE_REPO:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_REPO:latest; do
              sudo docker push $IMG
            done
          fi
